import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="yunxiao_cli")
    subparsers = parser.add_subparsers(dest="command")

    login_parser = subparsers.add_parser("login")
    login_subparsers = login_parser.add_subparsers(dest="login_command")
    login_token_parser = login_subparsers.add_parser("token")
    login_token_parser.add_argument("token")
    login_token_parser.add_argument("--account", required=True)

    profile_parser = subparsers.add_parser("profile")
    profile_subparsers = profile_parser.add_subparsers(dest="profile_command")
    profile_add_parser = profile_subparsers.add_parser("add")
    profile_add_parser.add_argument("name")
    profile_add_parser.add_argument("--account", required=True)
    profile_add_parser.add_argument("--org", required=True)
    profile_add_parser.add_argument("--project", required=True)
    profile_use_parser = profile_subparsers.add_parser("use")
    profile_use_parser.add_argument("name")
    profile_subparsers.add_parser("list")
    profile_show_parser = profile_subparsers.add_parser("show")
    profile_show_parser.add_argument("--profile")

    meta_parser = subparsers.add_parser("meta")
    meta_subparsers = meta_parser.add_subparsers(dest="meta_command")
    meta_reload_parser = meta_subparsers.add_parser("reload")
    meta_reload_parser.add_argument("--profile")
    meta_types_parser = meta_subparsers.add_parser("types")
    meta_types_parser.add_argument("--profile")
    meta_types_parser.add_argument("--category")
    meta_statuses_parser = meta_subparsers.add_parser("statuses")
    meta_statuses_parser.add_argument("--profile")
    meta_statuses_parser.add_argument("--category", required=True)
    meta_fields_parser = meta_subparsers.add_parser("fields")
    meta_fields_parser.add_argument("--profile")
    meta_fields_parser.add_argument("--category", required=True)

    project_parser = subparsers.add_parser("project")
    project_subparsers = project_parser.add_subparsers(dest="project_command")
    project_list_parser = project_subparsers.add_parser("list")
    project_list_parser.add_argument("--profile")
    project_list_parser.add_argument("--account")
    project_list_parser.add_argument("--org")
    project_get_parser = project_subparsers.add_parser("get")
    project_get_parser.add_argument("--profile")

    workitem_parser = subparsers.add_parser("workitem")
    workitem_subparsers = workitem_parser.add_subparsers(dest="workitem_command")
    workitem_create_parser = workitem_subparsers.add_parser("create")
    workitem_create_parser.add_argument("--profile")
    workitem_create_parser.add_argument("--category", required=True)
    workitem_create_parser.add_argument("--type")
    workitem_create_parser.add_argument("--subject", required=True)
    workitem_create_parser.add_argument("--desc")
    workitem_create_parser.add_argument("--desc-file")
    workitem_create_parser.add_argument("--parent")
    workitem_create_parser.add_argument("--assigned-to")

    workitem_get_parser = workitem_subparsers.add_parser("get")
    workitem_get_parser.add_argument("workitem_id")
    workitem_get_parser.add_argument("--profile")
    workitem_get_parser.add_argument("--no-comments", action="store_true")
    workitem_get_parser.add_argument("--with-parent", action="store_true")
    workitem_get_parser.add_argument("--no-attachments", action="store_true")

    workitem_mine_parser = workitem_subparsers.add_parser("mine")
    workitem_mine_parser.add_argument("--profile")
    workitem_mine_parser.add_argument("--category")

    workitem_search_parser = workitem_subparsers.add_parser("search")
    workitem_search_parser.add_argument("--profile")
    workitem_search_parser.add_argument("--category")
    workitem_search_parser.add_argument("--status")

    workitem_update_parser = workitem_subparsers.add_parser("update")
    workitem_update_parser.add_argument("workitem_id")
    workitem_update_parser.add_argument("--profile")
    workitem_update_parser.add_argument("--subject")
    workitem_update_parser.add_argument("--desc")
    workitem_update_parser.add_argument("--desc-file")
    workitem_update_parser.add_argument("--assigned-to")
    workitem_update_parser.add_argument("--status")
    workitem_update_parser.add_argument("--field", action="append")
    workitem_update_parser.add_argument("--field-json", action="append")

    workitem_transition_parser = workitem_subparsers.add_parser("transition")
    workitem_transition_parser.add_argument("workitem_id")
    workitem_transition_parser.add_argument("--profile")
    workitem_transition_parser.add_argument("--to", required=True)

    comment_parser = subparsers.add_parser("comment")
    comment_subparsers = comment_parser.add_subparsers(dest="comment_command")
    comment_add_parser = comment_subparsers.add_parser("add")
    comment_add_parser.add_argument("--profile")
    comment_add_parser.add_argument("--workitem", required=True)
    comment_add_parser.add_argument("--content", required=True)
    comment_list_parser = comment_subparsers.add_parser("list")
    comment_list_parser.add_argument("--profile")
    comment_list_parser.add_argument("--workitem", required=True)

    relation_parser = subparsers.add_parser("relation")
    relation_subparsers = relation_parser.add_subparsers(dest="relation_command")
    relation_add_parser = relation_subparsers.add_parser("add")
    relation_add_parser.add_argument("--profile")
    relation_add_parser.add_argument("--parent", required=True)
    relation_add_parser.add_argument("--child", required=True)
    relation_children_parser = relation_subparsers.add_parser("children")
    relation_children_parser.add_argument("--profile")
    relation_children_parser.add_argument("--parent", required=True)

    return parser
